[tool.ruff]
# Target Python version
target-version = "py310"

# Files to exclude
exclude = [
    ".git",
    ".venv",
    "venv",
    "frontend",
    "__pycache__",
    "node_modules",
]

# Line length setting
line-length = 100

[tool.ruff.lint]
# Enable specific rules
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions (optimizes list/dict comprehensions)
    "SIM",  # flake8-simplify (suggests code simplifications)
    "UP",   # pyupgrade (modernizes Python syntax)
    "N",    # pep8-naming (enforces consistent naming)
    "D",    # pydocstyle (docstring style checking)
]

# Ignore specific rules
ignore = ["B008", "D100", "D104"]  # Ignoring some docstring requirements to start

# Allow autofix for all enabled rules
fixable = ["ALL"]
unfixable = []

# Configure docstring settings
[tool.ruff.lint.pydocstyle]
convention = "google"  # Use Google-style docstrings
